"""Initial Commit

Revision ID: e17aba83ecbb
Revises: 
Create Date: 2022-04-08 14:55:43.753546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17aba83ecbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fsr1', sa.Integer(), nullable=False),
    sa.Column('fsr2', sa.Integer(), nullable=False),
    sa.Column('fsr3', sa.Integer(), nullable=False),
    sa.Column('fsr5', sa.Integer(), nullable=False),
    sa.Column('pred', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('value_db')
    # ### end Alembic commands ###
